### ISSUE TITLE
wrong type of argument

### ISSUE THREAD

**Issue by jw-miaem** [codesuki/add-node-modules-path#10]
Hi, 
I've recently started having issues when trying to open js files without node_modules. My config has a hook for when a js file is opened. Here is the debug output from emacs:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  add-node-modules-path()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook js-mode-hook js2-mode-hook js2-jsx-mode-hook rjsx-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook js-mode-hook js2-mode-hook js2-jsx-mode-hook rjsx-mode-hook))
  run-mode-hooks(rjsx-mode-hook)
  rjsx-mode()
  set-auto-mode-0(rjsx-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
```

I'm removing from config and just manually running if needed for now. Ideally would like to turn this feature back on

**Comment by codesuki** [comment]
I could reproduce this. Seems it came in with the latest PR. Let me see how I can fix that.

**Comment by codesuki** [comment]
Hopefully fixed in master. Please let me know if it's fixed for your, too.

**Comment by jw-miaem** [comment]
Fixed, thank you :+1:
