### ISSUE TITLE
Is this method insecure and, if yes, can we use `npm bin` ?

### ISSUE THREAD

**Issue by deb0ch** [codesuki/add-node-modules-path#15]
I have seen that this method being allegedly insecure [is a concern in Spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/javascript/README.org#node-modules), where they give a link to [this Stackoverflow thread](https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules#comment33532258_9683472).

An alternative, more secure solution would be to use `npm bin` to find the node_modules.

It would be great if your package could be used by default in Spacemacs, but I fear that this security issue would put off the dev team to do so until it is addressed or debunked.

What do you think about the security issue and the proposed alternative ?

**Comment by codesuki** [comment]
Thanks for the info.
Reading the spacemacs link it seems they already have support for adding node_modules.
Would they still need this library? 

I will have a look into `npm bin`.
Also feel free to send a PR because I am strapped for time.

**Comment by deb0ch** [comment]
The solution we had was your module, and it still is to this day but now disabled by default, which is inconvenient.

In the meantime, I have found and read [this spacemacs issue](https://github.com/syl20bnr/spacemacs/issues/9047), where they disabled by default the search using your module.

**Comment by codesuki** [comment]
I see! Thanks for the info :)
I will look into `npm bin`.

**Comment by zzantares** [comment]
FWIW if someone is paranoid like myself and only needing this package for `eslint` take a look at this [SO answer](https://emacs.stackexchange.com/a/21207), it doesn't fixes your paranoia but it alleviates it 😉 .

**Comment by ghost** [comment]
I changed from look for the `node_modules` path to `npm bin` and works great and it's a more simple approach (and faster), here the code https://framagit.org/distopico/dotemacs/-/blob/master/modes/conf-javascript.el#L109
