### ISSUE TITLE
Latest commit adds `s.el` dependency (`s-chomp`)

### ISSUE THREAD

**Issue by jletourneau** [codesuki/add-node-modules-path#19]
After upgrading `add-node-modules-path` to the latest repo commit (i.e. https://github.com/codesuki/add-node-modules-path/pull/16), Emacs 27.2 now throws an error: `File mode specification error: (void-function s-chomp)` when opening a file inside a project with a `node_modules` directory.

The error appears to stem from [this line](https://github.com/codesuki/add-node-modules-path/blob/master/add-node-modules-path.el#L55) which was added in the latest commit — `s-chomp` comes from `s.el` which is not yet bundled with Emacs.

**Comment by codesuki** [comment]
That is true! I guess adding a ```;; Package-Requires:``` header will fix this. `s.el` seems to have a lot of dependents already.
https://melpa.org/#/s

**Comment by codesuki** [comment]
https://github.com/codesuki/add-node-modules-path/releases/tag/1.3.1
Feel free to re-open if it does not work.
