### ISSUE TITLE
Requires global npm to work?

### ISSUE THREAD

**Issue by WillAyd** [codesuki/add-node-modules-path#21]
Hey thanks for this! In setting this up I noticed an issue however where this requires a global npm to work. When installing npm exclusively through an nvm environment and running this in debug mode I was getting 

```sh
Failed to run ‘npm bin’:
 /bin/bash: line 1: npm: command not found
```

Is there any way to make this work when using nvm exclusively?

**Comment by codesuki** [comment]
Can you try setting `add-node-modules-path-command` ?

**Comment by WillAyd** [comment]
That does work though I think is somewhat self-defeating to do `(setq add-node-modules-path-command "~/.nvm/versions/node/v16.16.0/bin/npm bin")` ? Or did you have something else in mind?

**Comment by codesuki** [comment]
I never used nvm so not sure how it works exactly but shouldn't it modify your path? I guess in the terminal you just use `npm` and it works right? So as long as the path is reflected in Emacs `npm` in emacs should also work.

**Comment by WillAyd** [comment]
That's correct. I figured out the issue - when starting the Emacs GUI it wasn't necessarily modifying the path in the same way that a user terminal session would. The [exec-path-from-shell package](https://github.com/purcell/exec-path-from-shell) helped solved this problem

I don't think this is an issue for this repo at all to tackle so going to close. Thanks for your help and the great package
