### ISSUE TITLE
Installation using use-package

### ISSUE THREAD

**Issue by am** [codesuki/add-node-modules-path#4]
Adding the package with [use-package](https://github.com/jwiegley/use-package):

```lisp
(use-package add-node-modules-path :ensure t)
```

For some reason I don't see the function exposed when running `M-x add-node-modules-path`.

Any idea what am I missing?

**Comment by codesuki** [comment]
The function doesn't have `(interactive)` in it, so it won't show up in M-x.
Maybe I should consider adding that.

You can still run it with `eval-expression` or adding the hooks it will run.

**Comment by codesuki** [comment]
Added the `interactive`. Should work with M-x now given you have the latest version `1.2.0`.
