### ISSUE TITLE
Issues with development branch of Spacemacs

### ISSUE THREAD

**Issue by tamoore** [codesuki/add-node-modules-path#7]
When using the develop branch of spacemacs, this function is no longer provided. Will try and work out what the issue is.

**Comment by codesuki** [comment]
Thanks! Let me know if you find the problem.

**Comment by efouladi** [comment]
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/javascript#node-modules

**Comment by clayrisser** [comment]
I am having the same problem

**Comment by clayrisser** [comment]
I want this to work with rjsx mode (the react layer)

**Comment by clayrisser** [comment]
This is the error I'm getting . . .

```el
File mode specification error: (void-function add-node-modules-path)
```

**Comment by codesuki** [comment]
Did you add this? 
```
(setq-default dotspacemacs-configuration-layers
  '((javascript :variables node-add-modules-path t)))
```

**Comment by clayrisser** [comment]
Where do I add it?

**Comment by codesuki** [comment]
In your emacs config.
Check https://github.com/codesuki/add-node-modules-path/issues/7#issuecomment-385388439 for more info.

**Comment by clayrisser** [comment]
Yes, but I need it to work with rjsx-mode, not javascript mode

**Comment by codesuki** [comment]
I don't know how spacemacs works so maybe you should open an issue there.
It seems the addon doesn't get loaded.
In general if you follow https://github.com/codesuki/add-node-modules-path#usage and just adapt for your mode it should work, given it's loaded.

**Comment by clayrisser** [comment]
I solve it the following way . . .

I add `add-node-modules-path` to `dotspacemacs-additional-packages` and then I register the following hooks in the user-init section.

```
  (add-hook 'javascript-mode-hook 'add-node-modules-path)
  (add-hook 'rjsx-mode-hook 'add-node-modules-path)
```

https://github.com/codejamninja/dotfiles/blob/master/linux/spacemacs/.spacemacs.d/init.el#L74
https://github.com/codejamninja/dotfiles/blob/master/linux/spacemacs/.spacemacs.d/init.el#L169
https://github.com/codejamninja/dotfiles/blob/master/linux/spacemacs/.spacemacs.d/init.el#L171
