### ISSUE TITLE
Recursive invocation

### ISSUE THREAD

**Issue by tilgovi** [codesuki/add-node-modules-path#8]
Would you accept a PR to make the function recursive? Particularly in monorepo projects I sometimes have multiple directory levels with node_modules and want every .bin on my path.

**Comment by codesuki** [comment]
Sure, as long as it still works the normal way 👍

**Comment by geoffp** [comment]
I found this just now because I had the same issue in a monorepo. :) Thanks for looking into this @tilgovi!
